version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    env_file:
      - ../.env  # Adjust the path to the .env file
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./populate_data.sql:/docker-entrypoint-initdb.d/populate_data.sql


volumes:
  postgres_data:

networks:
  my_network:
